#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Riff.Droid.Resource", IsApplication=true)]

namespace Riff.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int rotation = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int slide_up = 2130771969;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F020000
			public const int setting_theme_entries = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int setting_theme_entry_values = 2130837505;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int colorAccent = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int colorPrimary = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int colorPrimaryDark = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_launcher_background = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int photo_background = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int splash_background = 2130903045;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int activity_vertical_margin = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int fab_margin = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int nav_header_height = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int nav_header_vertical_spacing = 2130968580;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int circle = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_menu_album = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_menu_camera = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_menu_gallery = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int ic_menu_manage = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int ic_menu_search = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int ic_menu_send = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int ic_menu_share = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int ic_menu_slideshow = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int ic_search_artist = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int ic_search_genre = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int ic_sync_disabled = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int ic_sync_problem = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int ic_sync_started = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int ic_sync_uptodate = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int rounded_corners_card = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int side_nav_bar = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int splash_logo = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int splash_screen = 2131034130;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060003
			public const int albums_recycler_view = 2131099651;
			
			// aapt resource value: 0x7F060000
			public const int album_art = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int album_artist = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int album_name = 2131099650;
			
			// aapt resource value: 0x7F060006
			public const int artists_recycler_view = 2131099654;
			
			// aapt resource value: 0x7F060004
			public const int artist_initials = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int artist_name = 2131099653;
			
			// aapt resource value: 0x7F060007
			public const int card_view = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int content_frame = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int drawer_layout = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int fre_app_name = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int fre_login_button = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int fre_login_description = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int fre_logo = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int fre_next_button = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int fre_postlogin_email = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int fre_postlogin_layout = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int fre_postlogin_name = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int fre_postlogin_photo = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int fre_postlogin_progressbar = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int fre_root_layout = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int fre_spinner = 2131099669;
			
			// aapt resource value: 0x7F060018
			public const int genres_recycler_view = 2131099672;
			
			// aapt resource value: 0x7F060016
			public const int genre_initials = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int genre_name = 2131099671;
			
			// aapt resource value: 0x7F060019
			public const int menu_action_search = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int menu_action_sync_status = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int menu_group_bottom = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int menu_group_top = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int nav_home = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int nav_library = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int nav_recent_plays = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int nav_settings = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int nav_view = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int preference_is_sync_paused = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int profilePicture = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int search = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int search_item_art = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int search_item_description = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int search_item_name = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int search_result_list = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int settings_container = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int sliding_tabs = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int toolbar = 2131099691;
			
			// aapt resource value: 0x7F060030
			public const int tracks_recycler_view = 2131099696;
			
			// aapt resource value: 0x7F06002C
			public const int track_art = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int track_artist = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int track_duration = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int track_name = 2131099695;
			
			// aapt resource value: 0x7F060031
			public const int userEmail = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int userName = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int viewPager = 2131099699;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int activity_fre = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int activity_main = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int activity_search = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int activity_settings = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int fragment_home = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int fragment_musiclibrary = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int fragment_musiclibrary_albums = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int fragment_musiclibrary_artists = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int fragment_musiclibrary_genres = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int fragment_musiclibrary_tracks = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int fragment_recentplays = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int musiclibrary_artist_item = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int nav_header_main = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int sync_icon_image_view = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int widget_album_item = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int widget_artist_item = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int widget_genre_item = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int widget_search_item = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int widget_track_item = 2131165202;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080000
			public const int activity_main_drawer = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int menu_main = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int menu_search_activity = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int app_icon_round = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_icon_square = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int ic_launcher = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int ic_launcher_foreground = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int ic_launcher_round = 2131296260;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int action_settings = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int app_name = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int backend_preference_file_key = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int channel_descrioption = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int channel_name = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int fre_login_button_text = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int fre_login_description_text = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int fre_next_button_text = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int menu_item_home = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int menu_item_library = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int menu_item_recent_plays = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int menu_item_settings = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int menu_item_sync_status = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int navigation_drawer_close = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int navigation_drawer_open = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int preference_category_account = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int preference_category_downloading = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int preference_category_general = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int preference_category_playback = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int preference_key_deltaUrl = 2131361811;
			
			// aapt resource value: 0x7F0A0014
			public const int search_album_description = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public const int search_artist_description = 2131361813;
			
			// aapt resource value: 0x7F0A0016
			public const int search_genre_description = 2131361814;
			
			// aapt resource value: 0x7F0A0017
			public const int search_hint = 2131361815;
			
			// aapt resource value: 0x7F0A0018
			public const int search_title = 2131361816;
			
			// aapt resource value: 0x7F0A0019
			public const int search_track_description = 2131361817;
			
			// aapt resource value: 0x7F0A0024
			public const int settings_activity_title = 2131361828;
			
			// aapt resource value: 0x7F0A0025
			public const int settings_sign_in_to_onedrive = 2131361829;
			
			// aapt resource value: 0x7F0A0026
			public const int settings_sign_in_to_onedrive_summary = 2131361830;
			
			// aapt resource value: 0x7F0A0027
			public const int settings_sign_out_of_onedrive = 2131361831;
			
			// aapt resource value: 0x7F0A001A
			public const int setting_clear_downloaded_music = 2131361818;
			
			// aapt resource value: 0x7F0A001B
			public const int setting_clear_downloaded_music_summary = 2131361819;
			
			// aapt resource value: 0x7F0A001C
			public const int setting_download_over_wifi = 2131361820;
			
			// aapt resource value: 0x7F0A001D
			public const int setting_download_over_wifi_summary = 2131361821;
			
			// aapt resource value: 0x7F0A001E
			public const int setting_manage_downloaded_music = 2131361822;
			
			// aapt resource value: 0x7F0A001F
			public const int setting_pause_sync = 2131361823;
			
			// aapt resource value: 0x7F0A0020
			public const int setting_pause_sync_summary = 2131361824;
			
			// aapt resource value: 0x7F0A0021
			public const int setting_stream_over_wifi = 2131361825;
			
			// aapt resource value: 0x7F0A0022
			public const int setting_stream_over_wifi_summary = 2131361826;
			
			// aapt resource value: 0x7F0A0023
			public const int setting_theme = 2131361827;
			
			// aapt resource value: 0x7F0A0028
			public const int tab_albums = 2131361832;
			
			// aapt resource value: 0x7F0A0029
			public const int tab_artists = 2131361833;
			
			// aapt resource value: 0x7F0A002A
			public const int tab_genres = 2131361834;
			
			// aapt resource value: 0x7F0A002B
			public const int tab_playlists = 2131361835;
			
			// aapt resource value: 0x7F0A002C
			public const int tab_tracks = 2131361836;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int AppTheme_AppBarOverlay = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int AppTheme_Fre = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int AppTheme_NoActionBar = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int AppTheme_PopupOverlay = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int AppTheme_Splash = 2131427333;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int fragment_settings = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int searchable = 2131492865;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
